---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubelog
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kubelog
rules:
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: default-account-kubelog
subjects:
- kind: ServiceAccount
  name: kubelog
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubelog
  apiGroup: rbac.authorization.k8s.io
